language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - pip install -r requirements.test.txt
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
script:
    - coverage run tests.py
after_success:
    - coveralls
